version: '3.7'
networks:
  net:

services:
  memcached:
    command: -m 16
    container_name: memcached
    image: memcached:1.5.19-alpine
    networks:
      - net
    ports:
      - 11211:11211
    restart: always

  mysql:
    container_name: secretary-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-schedule_secretary}
      - MYSQL_USER=${MYSQL_USER:-charles}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-charles}
    image: mysql:5.7.28
    networks:
      - net
    ports:
      - 3307:3306
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  redis:
    command: --appendonly yes --auto-aof-rewrite-min-size 16mb --stop-writes-on-bgsave-error no
    container_name: redis
    image: redis:5.0.6-alpine
    networks:
      - net
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./db/redis/data:/data
